name: Deploy client

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v2
  
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '18.16.0'
  
    - name: Install Angular CLI
      run: npm install -g @angular/cli
  
    - name: Install npm dependencies
      run: npm install
  
    - name: Build Angular app
      run: ng build
  
    - name: Copy files to the server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        source: "dist/*"
        target: "/projects/balian-shop/client/balian-shop-client"

    - name: Restart service
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          sudo systemctl restart nginx
          


