name: Deploy client

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v2
  
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '18.16.0'
  
    - name: Change to src directory
      run: cd src

    - name: Install npm dependencies
      run: npm install
      working-directory: ./src
  
    - name: Build React app
      run: CI=false npm run build
      working-directory: ./src
  
    - name: Copy files to the server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        source: "src/build/*" 
        target: "/projects/balian-shop/client/balian-shop-client"

    - name: Restart service
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          sudo systemctl restart nginx
